name: main

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.50.0
          skip-go-installation: true
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Test
        run: go test -race -timeout=60s -v -coverprofile="coverage.txt" -covermode=atomic ./...
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt